# 向量检索配置
milvus:
  uri: http://localhost:19530
  token: null
  collection_name: medical_knowledge
  drop_old: false
  auto_id: false

embedding:
  summary_dense:
    provider: dashscope
    model: text-embedding-v2
    api_key: sk-9de21cd0776947ec9ef2396f7110cb6d
    base_url: https://dashscope.aliyuncs.com/api/v1/services/embeddings/text-embedding/text-embedding
    dimension: 1536
  text_dense:
    provider: dashscope
    model: text-embedding-v2
    api_key: sk-9de21cd0776947ec9ef2396f7110cb6d
    base_url: https://dashscope.aliyuncs.com/api/v1/services/embeddings/text-embedding/text-embedding
    dimension: 1536
  text_sparse:
    provider: self
    vocab_path_or_name: vocab.pkl.gz
    algorithm: BM25
    domain_model: medicine
    k1: 1.5
    b: 0.75
    build:
      workers: 8
      chunksize: 64
